### ISSUE TITLE
Add configurable disk usage threshold

### ISSUE THREAD

**Issue by jshufro** [gobitfly/eth2-client-metrics-exporter#13]
It seems like 80% is hardcoded for alerts, but it's noisy for my use-case. It would be ideal if the threshold were configurable at runtime.

**Comment by manuelsc** [comment]
iirc the default threshold for the disk usage notifications is 90%, you can configure custom thresholds if you have any active beaconcha.in premium subscription. One caveat though, It's not possible yet to change the threshold on web but you can easily do so in the app. Hope this helps

**Comment by jshufro** [comment]
Thanks, I found the setting in the mobile app
