### ISSUE TITLE
Request: eth2-client-metrics-exporter distributions

### ISSUE THREAD

**Issue by alexmbird** [gobitfly/eth2-client-metrics-exporter#8]
Following on from [this](https://github.com/gobitfly/eth2-beaconchain-explorer/issues/2209) (this metrics exporter client project didn't show up when I searched yesterday!)

I love eth2-client-metrics-exporter but running it from the command line is a pain and curl-pipe-bash scares me.  Can you publish it as something installable in a more conventional way?  

I'm thinking:

- An image on Docker Hub or equivalent so I can run it the same way as the rest of my stack
- And/or a .deb repo, for a client packaged with systemd unit files

CC-ing @recy21

**Comment by recy21** [comment]
Updated the internal ticket, so we will update here. Thanks :+1:

**Comment by alexmbird** [comment]
Oh!  While rolling back after a power outage (I really shouldn't be trusted to run a node) I had to reinstall the client and noticed from the readme in this repo you [already](https://github.com/gobitfly/eth2-client-metrics-exporter#example-with-docker) *do* support Docker.  Maybe all we need is a link from the beaconcha.in web frontend.

**Comment by recy21** [comment]
Lol, you are right :) Internal ticket closed :rofl: 

I'm not sure what you mean by the link? Why do we need a link?

**Comment by alexmbird** [comment]
What I mean is that I discovered the metrics exporter through https://www.beaconcha.in/user/settings#app.  I run Nimbus and it says to curl-pipe-bash to get the exported installed then run it from the command line.  It doesn't mention that there's a Docker image.

IMO you don't need to reproduce a full set of instructions for Docker, just mention that it's possible and give a link to the [example with docker](https://github.com/gobitfly/eth2-client-metrics-exporter#example-with-docker) in this project's readme file.

**Comment by recy21** [comment]
Will be part of next Release:
https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2216

**Comment by recy21** [comment]
Part of v1.24.0, already live on Goerli, will be part of Mainnet next week Tuesday.
